### PR TITLE
Adding REXForce protocol contracts

### PR DESCRIPTION
**Pull request by shreyaspapi**
Just a draft for -

- Captain Registration

- Dispute captain

- Onboard Captain

- Bounty creation and payout (Not started yet)

### CODE REVIEW

**Review by mikeghen — CHANGES_REQUESTED** [review]
This is great, a lot of the functionality is done and I see the TODOs where we still need to add some things. My only two requests for changes at the moment: 
1. Add some tests for the core functionality
2. Track how much RIC is staked by captains
3. Make sure bounty payments check the amount of RIC available, which is balanceOf - total captains staked amount

I will probably have some more thoughts but these are things after my first review of the contracts. Really great work, as usual, 😄

**Comment by mikeghen** [comment]
@shreyaspapi, do you have any updates to this PR?

**Comment by shreyaspapi** [comment]
@mikeghen As of now 0 progress. Since Saturday I had a mild sour throat which turned into Fever today. I think it will be best if you could progress on it this week.

**Comment by mikeghen** [comment]
Merged this in so we can start working in parallel on things. Up next is tests and making it a superapp, I will work on making it a superapp

**Comment by mikeghen** [comment]
Thanks @shreyaspapi and @nikramakrishnan for your work on this, very well done as usual 👏

**Pull request merged**
